#!/bin/bash
# -*- sh -*-

: << =cut

=head1 NAME

lxc_ram - Plugin to monitor LXC memory usage.

=head1 CONFIGURATION

No configuration

=head1 AUTHOR

vajtsz vajtsz@gmail.com

=head1 LICENSE

Unknown license

=head1 MAGIC MARKERS

 #%# family=auto
 #%# capabilities=autoconf

=cut

. $MUNIN_LIBDIR/plugins/plugin.sh

guest_names=`lxc-ls`

f_comm='lxc-cgroup  '

if [ "$1" = "autoconf" ]; then
	if [ -r /proc/stat ]; then
		echo yes
		exit 0
	else
		echo "no (no /proc/stat)"
		exit 0
	fi
fi

if [ "$1" = "config" ]; then

 echo 'graph_title Memory '
 echo 'graph_args -l 0 --base 1000'
 echo 'graph_vlabel byte'
 echo 'graph_category lxc'


 i=0
 for guest_name in $guest_names;
  do
   let i=i+1

   echo 'mem_usage_'$i'.label Mem usage '$guest_name
   echo 'mem_usage_'$i'.type GAUGE'
   echo 'mem_cache_'$i'.label Cache '$guest_name
   echo 'mem_cache_'$i'.type GAUGE'
   echo 'mem_active_'$i'.label Active '$guest_name
   echo 'mem_active_'$i'.type GAUGE'
   echo 'mem_inactive_'$i'.label Inactive '$guest_name
   echo 'mem_inactive_'$i'.type GAUGE'

  done
 
 exit 0
fi

 i=0
 for guest_name in $guest_names;
  do
   let i=i+1

   tmp_v=`$f_comm -n $guest_name memory.usage_in_bytes`
   echo 'mem_usage_'$i'.value '$tmp_v
   
   tmp_g=`$f_comm -n $guest_name memory.stat | grep total_cache`
   tmp_v=`echo $tmp_g | awk '{print($2)}'`
   echo  'mem_cache_'$i'.value '$tmp_v
   
   tmp_g=`$f_comm -n zimbrasrv memory.stat | grep total_active_anon`
   tmp_v=`echo $tmp_g | awk '{print($2)}'`
   echo  'mem_active_'$i'.value '$tmp_v
 
   tmp_g=`$f_comm -n zimbrasrv memory.stat | grep total_inactive_anon`
   tmp_v=`echo $tmp_g | awk '{print($2)}'`
   echo  'mem_inactive_'$i'.value '$tmp_v

  done
