#!/bin/bash
# -*- sh -*-

: << =cut

=head1 NAME

lxc_cpu - Plugin to monitor LXC CPU usage

=head1 CONFIGURATION

No configuration

=head1 AUTHOR

vajtsz  vajtsz@gmail.com

=head1 LICENSE

Unknown license

=head1 MAGIC MARKERS

 #%# family=auto
 #%# capabilities=autoconf

=cut

. $MUNIN_LIBDIR/plugins/plugin.sh

guest_names=`ls -d /var/lib/lxc/* | xargs -l basename`

f_comm='lxc-cgroup  '

if [ "$1" = "autoconf" ]; then
	if [ -r /proc/stat ]; then
		echo yes
		exit 0
	else
		echo "no (no /proc/stat)"
		exit 0
	fi
fi

if [ "$1" = "config" ]; then

 echo 'graph_title CPU Usage '
 echo 'graph_args -l 0 --base 1000'
 echo 'graph_vlabel USER_HZ'
 echo 'graph_category lxc'

 i=0
 for guest_name in $guest_names;
 do 
  let i=i+1
  echo 'cpu_user_'$i'.label User '$guest_name
  echo 'cpu_user_'$i'.type COUNTER'
  echo 'cpu_system_'$i'.label System '$guest_name
  echo 'cpu_system_'$i'.type COUNTER'
 done
 exit 0
fi

 i=0
 for guest_name in $guest_names;
 do 
  let i=i+1
  
  tmp_g=`$f_comm -n $guest_name cpuacct.stat | grep user`
  tmp_v=`echo $tmp_g | awk '{print($2)}'`
  echo 'cpu_user_'$i'.value $tmp_v'
  
  tmp_g=`$f_comm -n $guest_name cpuacct.stat | grep system`
  tmp_v=`echo $tmp_g | awk '{print($2)}'`
  echo 'cpu_system_'$i'.value $tmp_v'

 done


